// Define all available permissions in the system
export const PERMISSIONS = {
  // User Management
  MANAGE_USERS: 'manage_users',
  VIEW_USERS: 'view_users',
  
  // Vendor Management
  MANAGE_VENDORS: 'manage_vendors',
  VIEW_VENDORS: 'view_vendors',
  DELETE_VENDORS: 'delete_vendors',
  
  // Item Management
  MANAGE_ITEMS: 'manage_items',
  VIEW_ITEMS: 'view_items',
  DELETE_ITEMS: 'delete_items',
  
  // Purchase Invoices
  CREATE_PURCHASE_INVOICES: 'create_purchase_invoices',
  VIEW_PURCHASE_INVOICES: 'view_purchase_invoices',
  EDIT_PURCHASE_INVOICES: 'edit_purchase_invoices',
  DELETE_PURCHASE_INVOICES: 'delete_purchase_invoices',
  
  // Sales Invoices
  CREATE_SALES_INVOICES: 'create_sales_invoices',
  VIEW_SALES_INVOICES: 'view_sales_invoices',
  EDIT_SALES_INVOICES: 'edit_sales_invoices',
  DELETE_SALES_INVOICES: 'delete_sales_invoices',
  
  // Payments
  CREATE_PAYMENTS: 'create_payments',
  VIEW_PAYMENTS: 'view_payments',
  EDIT_PAYMENTS: 'edit_payments',
  DELETE_PAYMENTS: 'delete_payments',
  
  // Stock Management
  MANAGE_STOCK: 'manage_stock',
  VIEW_STOCK: 'view_stock',
  
  // Financial Reports & Ledgers
  VIEW_LEDGERS: 'view_ledgers',
  VIEW_REPORTS: 'view_reports',
  VIEW_CASHBOOK: 'view_cashbook',
  VIEW_BANKBOOK: 'view_bankbook',
  
  // Bank Accounts
  MANAGE_BANK_ACCOUNTS: 'manage_bank_accounts',
  VIEW_BANK_ACCOUNTS: 'view_bank_accounts',
  
  // System Settings
  MANAGE_SETTINGS: 'manage_settings',
  VIEW_SETTINGS: 'view_settings',
  
  // Dashboard & Analytics
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_ANALYTICS: 'view_analytics',
  
  // WhatsApp Integration
  MANAGE_WHATSAPP_SETTINGS: 'manage_whatsapp_settings',
  SEND_WHATSAPP_MESSAGES: 'send_whatsapp_messages',
  VIEW_WHATSAPP_LOGS: 'view_whatsapp_logs',
} as const;

// Define permissions for each role
export const ROLE_PERMISSIONS = {
  Admin: [
    // Full organization access
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.VIEW_VENDORS,
    PERMISSIONS.DELETE_VENDORS,
    PERMISSIONS.MANAGE_ITEMS,
    PERMISSIONS.VIEW_ITEMS,
    PERMISSIONS.DELETE_ITEMS,
    PERMISSIONS.CREATE_PURCHASE_INVOICES,
    PERMISSIONS.VIEW_PURCHASE_INVOICES,
    PERMISSIONS.EDIT_PURCHASE_INVOICES,
    PERMISSIONS.DELETE_PURCHASE_INVOICES,
    PERMISSIONS.CREATE_SALES_INVOICES,
    PERMISSIONS.VIEW_SALES_INVOICES,
    PERMISSIONS.EDIT_SALES_INVOICES,
    PERMISSIONS.DELETE_SALES_INVOICES,
    PERMISSIONS.CREATE_PAYMENTS,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.EDIT_PAYMENTS,
    PERMISSIONS.DELETE_PAYMENTS,
    PERMISSIONS.MANAGE_STOCK,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.VIEW_LEDGERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_CASHBOOK,
    PERMISSIONS.VIEW_BANKBOOK,
    PERMISSIONS.MANAGE_BANK_ACCOUNTS,
    PERMISSIONS.VIEW_BANK_ACCOUNTS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MANAGE_WHATSAPP_SETTINGS,
    PERMISSIONS.SEND_WHATSAPP_MESSAGES,
    PERMISSIONS.VIEW_WHATSAPP_LOGS,
  ],
  
  Operator: [
    // Operations focused permissions
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_VENDORS,
    PERMISSIONS.MANAGE_VENDORS, // Can add/edit vendors
    PERMISSIONS.VIEW_ITEMS,
    PERMISSIONS.MANAGE_ITEMS, // Can add/edit items
    PERMISSIONS.CREATE_PURCHASE_INVOICES,
    PERMISSIONS.VIEW_PURCHASE_INVOICES,
    PERMISSIONS.EDIT_PURCHASE_INVOICES,
    PERMISSIONS.CREATE_SALES_INVOICES,
    PERMISSIONS.VIEW_SALES_INVOICES,
    PERMISSIONS.EDIT_SALES_INVOICES,
    PERMISSIONS.CREATE_PAYMENTS,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.MANAGE_STOCK,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.VIEW_LEDGERS,
    PERMISSIONS.VIEW_BANK_ACCOUNTS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.SEND_WHATSAPP_MESSAGES,
    PERMISSIONS.VIEW_WHATSAPP_LOGS,
  ],
  
  Accountant: [
    // Finance focused permissions
    PERMISSIONS.VIEW_VENDORS,
    PERMISSIONS.VIEW_ITEMS,
    PERMISSIONS.VIEW_PURCHASE_INVOICES,
    PERMISSIONS.VIEW_SALES_INVOICES,
    PERMISSIONS.CREATE_PAYMENTS,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.EDIT_PAYMENTS,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.VIEW_LEDGERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_CASHBOOK,
    PERMISSIONS.VIEW_BANKBOOK,
    PERMISSIONS.VIEW_BANK_ACCOUNTS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.SEND_WHATSAPP_MESSAGES,
    PERMISSIONS.VIEW_WHATSAPP_LOGS,
  ],
} as const;